list=["BMW","Benz","Mclaren","Bentley","Morris Garage"]
print(list,type(list))
print("The first element is ",list[0])
print("The last element is ",list[-1])
print("The length of the list is ",len(list))
list.append("Lexus")
print(list)
list.remove("BMW")
print(list)
list.sort()
print(list)
list.reverse()
print(list)
print(list*4)
print(list[:4])
list.clear()
print(list)